name: graphes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Installer Graphviz et PlantUML
      - name: Installer les dépendances
        run: sudo apt-get update && sudo apt-get install -y graphviz plantuml

      # Étape 2 : Cloner le dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      # Étape 3 : Exécuter le script
      - name: Générer les graphes
        run: chmod +x graphiz1.sh && ./graphiz1.sh g1

      # Étape 4 : Uploader les fichiers en tant qu'artifacts
      - name: Uploader les résultats
        uses: actions/upload-artifact@v4
        with:
          name: graphes-generes
          path: "*.svg"
